language: node_js
node_js:
  - "0.10"
after_success: npm run docs
deploy:
  - provider: s3
    bucket: "fungusjs.com"
    local-dir: ".tmp/docs"
    skip_cleanup: true
    on:
      all_branches: true
      tags: true
    access_key_id:
      secure: BXZOvUbwjn5hCkAY0avjIj7m4WeNywBPmfjJgWHXYuwSxaMv9ztXf8QCziF3NuJsBv6eRtd/JwU+lSkAndMyK0VHAk7dWuAXRdnc9hf2HdRud3FqVHLaKDs8bkX62W5qPUOr2nYC/q46BNoXLU6Ux/5RxHoHrA3IGqUozcO4ptQ=
    secret_access_key:
      secure: cgsOBFlO91DiSCGCFwU6R9TzSpyW/vfpVSw9Org2zEUVcraV35UWKnsVlqmdvXQ8qUDE1QKFboiXzYmRXF953eDkd1zIN0YbaE10bLoc+wfw6kjrAy/BkpLiKPMcZsQdJizgQAIDFJgTt/0NP73SFzD3Ma7wpXMFZvjen8MhtSc=
  - provider: npm
    email: nathan@nathanhoule.com
    on:
      all_branches: true
      tags: true
    api_key:
      secure: f26oOEd9mQkzqOil0/hMU6cbiPomGP1y4v7dhRgcgSttpMpDgXLXOB9DSqw9cOZn6FHKXCuOIt2glRkwq59wkpF6Xsm/9vuZ7wx1uDmytvwFVqTy84oUUS8j0wMqh6MniIxfa7FVQD0u9IuSm7RovZddp40TwCr5HDXi8NOoB40=
