language: node_js
node_js:
  - "0.10"
before_script:
  - npm install -g bower
  - bower install
after_success: npm run docs
deploy:
  provider: s3
  access_key_id:
    secure: BXZOvUbwjn5hCkAY0avjIj7m4WeNywBPmfjJgWHXYuwSxaMv9ztXf8QCziF3NuJsBv6eRtd/JwU+lSkAndMyK0VHAk7dWuAXRdnc9hf2HdRud3FqVHLaKDs8bkX62W5qPUOr2nYC/q46BNoXLU6Ux/5RxHoHrA3IGqUozcO4ptQ=
  secret_access_key:
    secure: cgsOBFlO91DiSCGCFwU6R9TzSpyW/vfpVSw9Org2zEUVcraV35UWKnsVlqmdvXQ8qUDE1QKFboiXzYmRXF953eDkd1zIN0YbaE10bLoc+wfw6kjrAy/BkpLiKPMcZsQdJizgQAIDFJgTt/0NP73SFzD3Ma7wpXMFZvjen8MhtSc=
  local-dir: ".tmp/docs"
  skip_cleanup: true
  bucket: "fungusjs.com"
  endpoint: "fungusjs.com.s3-website-us-west-2.amazonaws.com"
  region: "us-west-2"
  on:
    all_branches: true
    tags: true
