#!/usr/bin/env node
'use strict';

var exec = require('exec-sync');
var path = require('path');

var BASE_DIR = exec('git rev-parse --show-toplevel');
var SRC_DIR = path.join(BASE_DIR, 'src');

require(path.join(BASE_DIR, 'docs/src'))({
  baseDir: BASE_DIR,
  srcDir: SRC_DIR
});
