#!/usr/bin/env bash

set -o errexit
set -o nounset

WATCHMAN=$(which watchman)
BASE_DIR=$(git rev-parse --show-toplevel)
SRC_DIR=${BASE_DIR}/lib

if [[ ! -x $WATCHMAN ]]; then
  echo "ERROR: Watchman binary not found. Please install watchman and try again."
  exit 1
fi

watchman trigger-del $SRC_DIR assets
watchman trigger-del $SRC_DIR docs
