#!/usr/bin/env bash

set -o errexit
set -o nounset

WATCHMAN=$(which watchman)
BASE_DIR=$(git rev-parse --show-toplevel)
SRC_DIR=${BASE_DIR}/src

if [[ ! -x $WATCHMAN ]]; then
  echo "ERROR: Watchman binary not found. Please install watchman and try again."
  exit 1
fi

# Rebuild source on filechanges
watchman -j <<-EOT
[
  "trigger", "$SRC_DIR", {
    "name": "assets",
    "expression": ["pcre", "\\\.js$"],
    "chdir": "$BASE_DIR",
    "command": ["make"]
  }
]
EOT

# Rebuild docs on filechanges
watchman -j <<-EOT
[
  "trigger", "$SRC_DIR", {
    "name": "docs",
    "expression": ["pcre", "\\\.js$"],
    "chdir": "$BASE_DIR",
    "command": ["make", "docs"]
  }
]
EOT
